import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
test('sample models and optional SDK adapters initialize without making network requests', async () => {
    const window = new JSDOM('<html><head></head><body></body></html>').window;
    globalThis.window = window; globalThis.document = window.document;
    try {
        const {default: mediator} = await import('../dist/app/assets/script/mediator/global.js');
        const {default: model} = await import('../dist/app/assets/script/model/singletons/global.js');
        const {default: countries} = await import('../dist/app/assets/script/model/singletons/countries.js');
        const {default: states} = await import('../dist/app/assets/script/model/singletons/states.js');
        const {default: User} = await import('../dist/app/assets/script/model/user.js');
        assert.ok(countries.get().length > 100); assert.ok(states.get().length > 40);
        assert.equal(new User({name: 'Ada'}).get().name, 'Ada');
        assert.equal(model.get().service, '/service-endpoint');
        await import('../dist/app/assets/script/index.js');
        await import('../dist/app/assets/script/toolkit.js?empty');
        assert.equal(document.querySelector('script'), null);
        const {default: Facebook} = await import('../dist/app/assets/script/api/facebook.js');
        const fb = new Facebook();
        fb.initialize(); fb.initialize();
        assert.equal(document.querySelectorAll('#facebook-jssdk').length, 1);
        let fbOptions;
        let fbReady = 0;
        window.FB = {init(options) {fbOptions = options;}, AppEvents: {logPageView() {}}};
        mediator.on('facebook-api-1:state:ready', () => fbReady++);
        window.fbAsyncInit();
        assert.equal(fbOptions.appId, null);
        model.set({appId: 'example-app'});
        window.fbAsyncInit();
        assert.equal(fbOptions.appId, 'example-app'); assert.equal(fbReady, 2);
        document.querySelector('#facebook-jssdk').remove();
        document.head.append(document.createElement('script'));
        fb.initialize();
        assert.equal(document.head.firstChild.id, 'facebook-jssdk');
        document.body.innerHTML = '<div class="youtube-player-1"></div>';
        await import('../dist/app/assets/script/toolkit.js?player');
        assert.ok(document.querySelector('script[src="//www.youtube.com/iframe_api"]'));
        let youtubeReady = false;
        mediator.once('youtube-api-1:state:ready', () => youtubeReady = true);
        window.onYouTubeIframeAPIReady();
        assert.equal(youtubeReady, true);
        const {default: Player} = await import('../dist/app/assets/script/view/toolkit/youtube-player-1.js');
        const player = new Player();
        assert.equal(player.parentElement, document.body);
        player.initialize(); player.addListeners(); player.removeListners();
        document.body.remove();
        assert.equal(new Player().parentElement, undefined);
        mediator.removeAllListeners();
    } finally {delete globalThis.window; delete globalThis.document; window.close();}
});
