nodeLinker: node-modules
approvedGitRepositories:
  - "https://github.com/bshack/white-label-mediator.git"
  - "https://github.com/bshack/white-label-model.git"
  - "https://github.com/bshack/white-label-router.git"
  - "https://github.com/bshack/white-label-view.git"
